/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConfigureDatadisBody,
  ConfigureShellyBody,
  GetDatadisConfigResponse,
  GetDatadisConsumptionHourlyCsvReportParams,
  GetShellyConfigResponse,
  SyncDatadisConsumptionsBody,
  SyncMonthlyDatadisConsumptionsBody,
  SyncYearlyDatadisConsumptionsBody
} from '.././models';

import { customInstance } from '.././custom-instance';
import type { ErrorType } from '.././custom-instance';




/**
 * This endpoint returns the Shelly integration configuration for a specific community.

Authentication is mandated, utilizing an authentication token, to ensure secure access.
**Required: Community Admin**

Upon successful request, the server responds with an HTTP status code of 200, along with
the current configuration. If no configuration has been set yet, a 404 is returned.

 * @summary Returns the Shelly configuration for the specified community.
 */
export const getShellyConfig = (
    communityId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetShellyConfigResponse>(
      {url: `/api/v1/communities/${communityId}/config/shelly`, method: 'GET', signal
    },
      );
    }
  

export const getGetShellyConfigQueryKey = (communityId: string,) => {
    return [`/api/v1/communities/${communityId}/config/shelly`] as const;
    }

    
export const getGetShellyConfigQueryOptions = <TData = Awaited<ReturnType<typeof getShellyConfig>>, TError = ErrorType<unknown>>(communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShellyConfig>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetShellyConfigQueryKey(communityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getShellyConfig>>> = ({ signal }) => getShellyConfig(communityId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(communityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getShellyConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetShellyConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getShellyConfig>>>
export type GetShellyConfigQueryError = ErrorType<unknown>


export function useGetShellyConfig<TData = Awaited<ReturnType<typeof getShellyConfig>>, TError = ErrorType<unknown>>(
 communityId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShellyConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShellyConfig>>,
          TError,
          Awaited<ReturnType<typeof getShellyConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShellyConfig<TData = Awaited<ReturnType<typeof getShellyConfig>>, TError = ErrorType<unknown>>(
 communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShellyConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getShellyConfig>>,
          TError,
          Awaited<ReturnType<typeof getShellyConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetShellyConfig<TData = Awaited<ReturnType<typeof getShellyConfig>>, TError = ErrorType<unknown>>(
 communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShellyConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the Shelly configuration for the specified community.
 */

export function useGetShellyConfig<TData = Awaited<ReturnType<typeof getShellyConfig>>, TError = ErrorType<unknown>>(
 communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getShellyConfig>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetShellyConfigQueryOptions(communityId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * This endpoint allows to enable or disable the Shelly integration for the energy community.

The request body must contain:
- **enabled** (required, boolean): Master switch for every Shelly-related
  services. When `false`, scheduled jobs for processing MQTT messages and
  aggregating hourly consumption are skipped. Set this to `false` for energy
  communities that do not have Shelly meters installed.

This configuration is a mandatory step to be able to process Shelly consumption data.

Authentication is mandated, utilizing an authentication token, to ensure secure access.
**Required: Community Admin**

Upon successful request, the server responds with an HTTP status code of 200, along with details
about the configuration already set.

In cases where the creation process encounters errors, the server responds with an appropriate error
status code, accompanied by a descriptive error message to guide clients in addressing and resolving the issue.

 * @summary Sets up the Shelly configuration for the specified community.
 */
export const configureShelly = (
    communityId: string,
    configureShellyBody: ConfigureShellyBody,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/communities/${communityId}/config/shelly`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: configureShellyBody
    },
      );
    }
  


export const getConfigureShellyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof configureShelly>>, TError,{communityId: string;data: ConfigureShellyBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof configureShelly>>, TError,{communityId: string;data: ConfigureShellyBody}, TContext> => {

const mutationKey = ['configureShelly'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof configureShelly>>, {communityId: string;data: ConfigureShellyBody}> = (props) => {
          const {communityId,data} = props ?? {};

          return  configureShelly(communityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfigureShellyMutationResult = NonNullable<Awaited<ReturnType<typeof configureShelly>>>
    export type ConfigureShellyMutationBody = ConfigureShellyBody
    export type ConfigureShellyMutationError = ErrorType<unknown>

    /**
 * @summary Sets up the Shelly configuration for the specified community.
 */
export const useConfigureShelly = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof configureShelly>>, TError,{communityId: string;data: ConfigureShellyBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof configureShelly>>,
        TError,
        {communityId: string;data: ConfigureShellyBody},
        TContext
      > => {

      const mutationOptions = getConfigureShellyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * This endpoint returns the Datadis connection configuration for a specific community.

The password is never returned in the response. Instead, a boolean field
`passwordSet` indicates whether a password has been configured.

Authentication is mandated, utilizing an authentication token, to ensure secure access.
**Required: Community Admin**

Upon successful request, the server responds with an HTTP status code of 200, along with
the current configuration. If no configuration has been set yet, a 404 is returned.

 * @summary Returns the Datadis configuration for the specified community.
 */
export const getDatadisConfig = (
    communityId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetDatadisConfigResponse>(
      {url: `/api/v1/communities/${communityId}/config/datadis`, method: 'GET', signal
    },
      );
    }
  

export const getGetDatadisConfigQueryKey = (communityId: string,) => {
    return [`/api/v1/communities/${communityId}/config/datadis`] as const;
    }

    
export const getGetDatadisConfigQueryOptions = <TData = Awaited<ReturnType<typeof getDatadisConfig>>, TError = ErrorType<unknown>>(communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatadisConfig>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDatadisConfigQueryKey(communityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDatadisConfig>>> = ({ signal }) => getDatadisConfig(communityId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(communityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDatadisConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDatadisConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getDatadisConfig>>>
export type GetDatadisConfigQueryError = ErrorType<unknown>


export function useGetDatadisConfig<TData = Awaited<ReturnType<typeof getDatadisConfig>>, TError = ErrorType<unknown>>(
 communityId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatadisConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDatadisConfig>>,
          TError,
          Awaited<ReturnType<typeof getDatadisConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDatadisConfig<TData = Awaited<ReturnType<typeof getDatadisConfig>>, TError = ErrorType<unknown>>(
 communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatadisConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDatadisConfig>>,
          TError,
          Awaited<ReturnType<typeof getDatadisConfig>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDatadisConfig<TData = Awaited<ReturnType<typeof getDatadisConfig>>, TError = ErrorType<unknown>>(
 communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatadisConfig>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the Datadis configuration for the specified community.
 */

export function useGetDatadisConfig<TData = Awaited<ReturnType<typeof getDatadisConfig>>, TError = ErrorType<unknown>>(
 communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatadisConfig>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDatadisConfigQueryOptions(communityId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * This endpoint allows to configure the app to connect with datadis for a specific community.

This configuration is a mandatory step to be able to retrieve consumption data from datadis.

Authentication is mandated, utilizing an authentication token, to ensure secure access.
**Required: Community Admin**

Upon successful request, the server responds with an HTTP status code of 200, along with details
about the configuration already set.

In cases where the creation process encounters errors, the server responds with an appropriate error
status code, accompanied by a descriptive error message to guide clients in addressing and resolving
the issue.

 * @summary Sets up the Datadis configuration for the specified community.
 */
export const configureDatadis = (
    communityId: string,
    configureDatadisBody: ConfigureDatadisBody,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/communities/${communityId}/config/datadis`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: configureDatadisBody
    },
      );
    }
  


export const getConfigureDatadisMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof configureDatadis>>, TError,{communityId: string;data: ConfigureDatadisBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof configureDatadis>>, TError,{communityId: string;data: ConfigureDatadisBody}, TContext> => {

const mutationKey = ['configureDatadis'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof configureDatadis>>, {communityId: string;data: ConfigureDatadisBody}> = (props) => {
          const {communityId,data} = props ?? {};

          return  configureDatadis(communityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfigureDatadisMutationResult = NonNullable<Awaited<ReturnType<typeof configureDatadis>>>
    export type ConfigureDatadisMutationBody = ConfigureDatadisBody
    export type ConfigureDatadisMutationError = ErrorType<unknown>

    /**
 * @summary Sets up the Datadis configuration for the specified community.
 */
export const useConfigureDatadis = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof configureDatadis>>, TError,{communityId: string;data: ConfigureDatadisBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof configureDatadis>>,
        TError,
        {communityId: string;data: ConfigureDatadisBody},
        TContext
      > => {

      const mutationOptions = getConfigureDatadisMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * This endpoint enables users to synchronize consumption data from datadis for a specific year.

The request body must contain:
- **year** (required, integer): The year for which to synchronize consumption data
- **supplyCode** (optional, string): The supply code (CUPS) to synchronize. If not provided, all active supplies will be synchronized.

The synchronization will retrieve data from January 1st to December 31st of the specified year.

**Behavior:**
- If supplyCode is provided: Synchronizes only that specific supply
- If supplyCode is not provided or is empty: Synchronizes all active supplies

The community is taken from the path; the configured Datadis credentials of that
community are used and only that community's supplies are synchronized.

Proper authentication, through an authentication token, is required for secure access to this endpoint.
**Required: Community Admin of the community. Returns 404 if the community does not exist or the
caller is not a member of it, or 403 if the caller is a member but not one of its admins.**

A successful request returns an HTTP status code of 200.

In cases of errors, the server responds with an appropriate error status code accompanied by a
descriptive message to guide users in resolving any issues.

 * @summary Synchronize the consumptions for a specific year from datadis, optionally filtering by supply code.
 */
export const syncDatadisConsumptions = (
    communityId: string,
    syncDatadisConsumptionsBody: SyncDatadisConsumptionsBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/communities/${communityId}/consumption/datadis/sync`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: syncDatadisConsumptionsBody, signal
    },
      );
    }
  


export const getSyncDatadisConsumptionsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncDatadisConsumptions>>, TError,{communityId: string;data: SyncDatadisConsumptionsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof syncDatadisConsumptions>>, TError,{communityId: string;data: SyncDatadisConsumptionsBody}, TContext> => {

const mutationKey = ['syncDatadisConsumptions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncDatadisConsumptions>>, {communityId: string;data: SyncDatadisConsumptionsBody}> = (props) => {
          const {communityId,data} = props ?? {};

          return  syncDatadisConsumptions(communityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SyncDatadisConsumptionsMutationResult = NonNullable<Awaited<ReturnType<typeof syncDatadisConsumptions>>>
    export type SyncDatadisConsumptionsMutationBody = SyncDatadisConsumptionsBody
    export type SyncDatadisConsumptionsMutationError = ErrorType<unknown>

    /**
 * @summary Synchronize the consumptions for a specific year from datadis, optionally filtering by supply code.
 */
export const useSyncDatadisConsumptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncDatadisConsumptions>>, TError,{communityId: string;data: SyncDatadisConsumptionsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncDatadisConsumptions>>,
        TError,
        {communityId: string;data: SyncDatadisConsumptionsBody},
        TContext
      > => {

      const mutationOptions = getSyncDatadisConsumptionsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * This endpoint enables admins to sync monthly consumption data into yearly totals.

The request body must contain:
- **year** (required, integer): The year for which to aggregate data
- **supplyCode** (optional, string): The supply code (CUPS) to aggregate. If not provided, all active supplies will be aggregated.

**Behavior:**
- If supplyCode is provided: Aggregates only that specific supply
- If supplyCode is not provided or is empty: Aggregates all active supplies

**Note:** This aggregation requires that monthly aggregations have already been performed
for the specified year.

The community is taken from the path and only that community's supplies are aggregated.

Proper authentication, through an authentication token, is required for secure access to this endpoint.
**Required: Community Admin of the community. Returns 404 if the community does not exist or the
caller is not a member of it, or 403 if the caller is a member but not one of its admins.**

A successful request returns an HTTP status code of 200.

 * @summary Sync monthly Datadis consumption data into yearly totals
 */
export const syncYearlyDatadisConsumptions = (
    communityId: string,
    syncYearlyDatadisConsumptionsBody: SyncYearlyDatadisConsumptionsBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/communities/${communityId}/consumption/datadis/sync/yearly`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: syncYearlyDatadisConsumptionsBody, signal
    },
      );
    }
  


export const getSyncYearlyDatadisConsumptionsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncYearlyDatadisConsumptions>>, TError,{communityId: string;data: SyncYearlyDatadisConsumptionsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof syncYearlyDatadisConsumptions>>, TError,{communityId: string;data: SyncYearlyDatadisConsumptionsBody}, TContext> => {

const mutationKey = ['syncYearlyDatadisConsumptions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncYearlyDatadisConsumptions>>, {communityId: string;data: SyncYearlyDatadisConsumptionsBody}> = (props) => {
          const {communityId,data} = props ?? {};

          return  syncYearlyDatadisConsumptions(communityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SyncYearlyDatadisConsumptionsMutationResult = NonNullable<Awaited<ReturnType<typeof syncYearlyDatadisConsumptions>>>
    export type SyncYearlyDatadisConsumptionsMutationBody = SyncYearlyDatadisConsumptionsBody
    export type SyncYearlyDatadisConsumptionsMutationError = ErrorType<unknown>

    /**
 * @summary Sync monthly Datadis consumption data into yearly totals
 */
export const useSyncYearlyDatadisConsumptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncYearlyDatadisConsumptions>>, TError,{communityId: string;data: SyncYearlyDatadisConsumptionsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncYearlyDatadisConsumptions>>,
        TError,
        {communityId: string;data: SyncYearlyDatadisConsumptionsBody},
        TContext
      > => {

      const mutationOptions = getSyncYearlyDatadisConsumptionsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * This endpoint enables admins to aggregate hourly consumption data into monthly totals.

The request body must contain:
- **year** (required, integer): The year for which to aggregate data
- **month** (optional, integer 1-12): The month to aggregate. If not provided, all months of the year will be aggregated.
- **supplyCode** (optional, string): The supply code (CUPS) to aggregate. If not provided, all active supplies will be aggregated.

**Behavior:**
- If both month and supplyCode are provided: Aggregates only that specific supply for that month
- If only month is provided: Aggregates all supplies for that specific month
- If only supplyCode is provided: Aggregates that supply for all months of the year
- If neither month nor supplyCode is provided: Aggregates all supplies for all months of the year

The community is taken from the path and only that community's supplies are aggregated.

Proper authentication, through an authentication token, is required for secure access to this endpoint.
**Required: Community Admin of the community. Returns 404 if the community does not exist or the
caller is not a member of it, or 403 if the caller is a member but not one of its admins.**

A successful request returns an HTTP status code of 200.

 * @summary Aggregate hourly Datadis consumption data into monthly totals
 */
export const syncMonthlyDatadisConsumptions = (
    communityId: string,
    syncMonthlyDatadisConsumptionsBody: SyncMonthlyDatadisConsumptionsBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/communities/${communityId}/consumption/datadis/sync/monthly`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: syncMonthlyDatadisConsumptionsBody, signal
    },
      );
    }
  


export const getSyncMonthlyDatadisConsumptionsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncMonthlyDatadisConsumptions>>, TError,{communityId: string;data: SyncMonthlyDatadisConsumptionsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof syncMonthlyDatadisConsumptions>>, TError,{communityId: string;data: SyncMonthlyDatadisConsumptionsBody}, TContext> => {

const mutationKey = ['syncMonthlyDatadisConsumptions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncMonthlyDatadisConsumptions>>, {communityId: string;data: SyncMonthlyDatadisConsumptionsBody}> = (props) => {
          const {communityId,data} = props ?? {};

          return  syncMonthlyDatadisConsumptions(communityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SyncMonthlyDatadisConsumptionsMutationResult = NonNullable<Awaited<ReturnType<typeof syncMonthlyDatadisConsumptions>>>
    export type SyncMonthlyDatadisConsumptionsMutationBody = SyncMonthlyDatadisConsumptionsBody
    export type SyncMonthlyDatadisConsumptionsMutationError = ErrorType<unknown>

    /**
 * @summary Aggregate hourly Datadis consumption data into monthly totals
 */
export const useSyncMonthlyDatadisConsumptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncMonthlyDatadisConsumptions>>, TError,{communityId: string;data: SyncMonthlyDatadisConsumptionsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncMonthlyDatadisConsumptions>>,
        TError,
        {communityId: string;data: SyncMonthlyDatadisConsumptionsBody},
        TContext
      > => {

      const mutationOptions = getSyncMonthlyDatadisConsumptionsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Retrieves hourly consumption data for the supplies of the community identified by the path
`communityId` within the specified date range and returns the result as a downloadable CSV file.

**Authorization Rules:**
- Only a Community Admin of the community can access this endpoint.
- Returns 404 if the community does not exist or the caller is not a member of it,
  or 403 if the caller is a member of the community but not one of its admins.

The CSV includes:
- cups: Supply point identifier
- date: Date of the consumption record
- time: Time of the consumption record
- consumptionKWh: Total consumption in kWh
- obtainMethod: Real or Estimated
- surplusEnergyKWh: Energy sent to the grid in kWh
- generationEnergyKWh: Generated energy in kWh
- selfConsumptionEnergyKWh: Self-consumed energy in kWh

 * @summary Exports hourly consumption data of a community's supplies as a CSV file
 */
export const getDatadisConsumptionHourlyCsvReport = (
    communityId: string,
    params: GetDatadisConsumptionHourlyCsvReportParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/v1/communities/${communityId}/consumption/datadis/report/hourly/csv`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetDatadisConsumptionHourlyCsvReportQueryKey = (communityId: string,
    params: GetDatadisConsumptionHourlyCsvReportParams,) => {
    return [`/api/v1/communities/${communityId}/consumption/datadis/report/hourly/csv`, ...(params ? [params]: [])] as const;
    }

    
export const getGetDatadisConsumptionHourlyCsvReportQueryOptions = <TData = Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError = ErrorType<unknown>>(communityId: string,
    params: GetDatadisConsumptionHourlyCsvReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDatadisConsumptionHourlyCsvReportQueryKey(communityId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>> = ({ signal }) => getDatadisConsumptionHourlyCsvReport(communityId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(communityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDatadisConsumptionHourlyCsvReportQueryResult = NonNullable<Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>>
export type GetDatadisConsumptionHourlyCsvReportQueryError = ErrorType<unknown>


export function useGetDatadisConsumptionHourlyCsvReport<TData = Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError = ErrorType<unknown>>(
 communityId: string,
    params: GetDatadisConsumptionHourlyCsvReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>,
          TError,
          Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDatadisConsumptionHourlyCsvReport<TData = Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError = ErrorType<unknown>>(
 communityId: string,
    params: GetDatadisConsumptionHourlyCsvReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>,
          TError,
          Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDatadisConsumptionHourlyCsvReport<TData = Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError = ErrorType<unknown>>(
 communityId: string,
    params: GetDatadisConsumptionHourlyCsvReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Exports hourly consumption data of a community's supplies as a CSV file
 */

export function useGetDatadisConsumptionHourlyCsvReport<TData = Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError = ErrorType<unknown>>(
 communityId: string,
    params: GetDatadisConsumptionHourlyCsvReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatadisConsumptionHourlyCsvReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDatadisConsumptionHourlyCsvReportQueryOptions(communityId,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



