/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateMembershipBody,
  GetMembershipEnergyMetricsParams,
  MembershipEnergyMetricsResponse,
  MembershipPaybackResponse,
  MembershipResponse,
  RestError,
  SetMembershipInvestmentBody,
  UpdateMembershipRoleBody
} from '.././models';

import { customInstance } from '.././custom-instance';
import type { ErrorType } from '.././custom-instance';




/**
 * Sets the amount, in euros, that this member initially contributed to the
community, replacing any amount previously recorded. Only the current value is
kept: there is no history of changes.

The amount must be greater than zero with at most two decimals. Requires
COMMUNITY_ADMIN of this community; platform admins who do not administer this
community are not granted access, and are answered 404 rather than 403 so the
membership's existence is not disclosed.

Answers 204 with no body. Read the stored amount back through the membership's
payback endpoint.

 * @summary Records a membership's initial investment.
 */
export const setMembershipInvestment = (
    communityId: string,
    userId: string,
    setMembershipInvestmentBody: SetMembershipInvestmentBody,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/communities/${communityId}/memberships/${userId}/investment`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setMembershipInvestmentBody
    },
      );
    }
  


export const getSetMembershipInvestmentMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setMembershipInvestment>>, TError,{communityId: string;userId: string;data: SetMembershipInvestmentBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof setMembershipInvestment>>, TError,{communityId: string;userId: string;data: SetMembershipInvestmentBody}, TContext> => {

const mutationKey = ['setMembershipInvestment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setMembershipInvestment>>, {communityId: string;userId: string;data: SetMembershipInvestmentBody}> = (props) => {
          const {communityId,userId,data} = props ?? {};

          return  setMembershipInvestment(communityId,userId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SetMembershipInvestmentMutationResult = NonNullable<Awaited<ReturnType<typeof setMembershipInvestment>>>
    export type SetMembershipInvestmentMutationBody = SetMembershipInvestmentBody
    export type SetMembershipInvestmentMutationError = ErrorType<unknown>

    /**
 * @summary Records a membership's initial investment.
 */
export const useSetMembershipInvestment = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setMembershipInvestment>>, TError,{communityId: string;userId: string;data: SetMembershipInvestmentBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setMembershipInvestment>>,
        TError,
        {communityId: string;userId: string;data: SetMembershipInvestmentBody},
        TContext
      > => {

      const mutationOptions = getSetMembershipInvestmentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Clears the amount recorded for this member, returning the membership to having
no investment. Payback then reports no investment rather than an investment of
zero, which are different statements.

Idempotent: clearing a membership that has no investment succeeds, because the
end state is the one the caller asked for. Requires COMMUNITY_ADMIN of this
community, with the same 404-not-403 mapping as the write.

 * @summary Removes a membership's initial investment.
 */
export const clearMembershipInvestment = (
    communityId: string,
    userId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/communities/${communityId}/memberships/${userId}/investment`, method: 'DELETE'
    },
      );
    }
  


export const getClearMembershipInvestmentMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearMembershipInvestment>>, TError,{communityId: string;userId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof clearMembershipInvestment>>, TError,{communityId: string;userId: string}, TContext> => {

const mutationKey = ['clearMembershipInvestment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clearMembershipInvestment>>, {communityId: string;userId: string}> = (props) => {
          const {communityId,userId} = props ?? {};

          return  clearMembershipInvestment(communityId,userId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ClearMembershipInvestmentMutationResult = NonNullable<Awaited<ReturnType<typeof clearMembershipInvestment>>>
    
    export type ClearMembershipInvestmentMutationError = ErrorType<unknown>

    /**
 * @summary Removes a membership's initial investment.
 */
export const useClearMembershipInvestment = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearMembershipInvestment>>, TError,{communityId: string;userId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clearMembershipInvestment>>,
        TError,
        {communityId: string;userId: string},
        TContext
      > => {

      const mutationOptions = getClearMembershipInvestmentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns the list of memberships for the specified community. Requires COMMUNITY_ADMIN or PLATFORM_ADMIN.
 * @summary Lists all memberships of a community.
 */
export const getMemberships = (
    communityId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MembershipResponse[]>(
      {url: `/api/v1/communities/${communityId}/memberships`, method: 'GET', signal
    },
      );
    }
  



export const getGetMembershipsQueryKey = (communityId?: string,) => {
    return [
    `/api/v1/communities/${communityId}/memberships`
    ] as const;
    }

    
export const getGetMembershipsQueryOptions = <TData = Awaited<ReturnType<typeof getMemberships>>, TError = ErrorType<unknown>>(communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemberships>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMembershipsQueryKey(communityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMemberships>>> = ({ signal }) => getMemberships(communityId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(communityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMemberships>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMembershipsQueryResult = NonNullable<Awaited<ReturnType<typeof getMemberships>>>
export type GetMembershipsQueryError = ErrorType<unknown>


export function useGetMemberships<TData = Awaited<ReturnType<typeof getMemberships>>, TError = ErrorType<unknown>>(
 communityId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemberships>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMemberships>>,
          TError,
          Awaited<ReturnType<typeof getMemberships>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMemberships<TData = Awaited<ReturnType<typeof getMemberships>>, TError = ErrorType<unknown>>(
 communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemberships>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMemberships>>,
          TError,
          Awaited<ReturnType<typeof getMemberships>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMemberships<TData = Awaited<ReturnType<typeof getMemberships>>, TError = ErrorType<unknown>>(
 communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemberships>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lists all memberships of a community.
 */

export function useGetMemberships<TData = Awaited<ReturnType<typeof getMemberships>>, TError = ErrorType<unknown>>(
 communityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemberships>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMembershipsQueryOptions(communityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Adds a user as a member of the specified community with the given role.
Requires COMMUNITY_ADMIN role in the community or PLATFORM_ADMIN.

A user can hold at most one membership per community, so adding one who is
already a member responds 409 with the `MEMBERSHIP_ALREADY_EXISTS` code. Use
the role PATCH to change an existing member's role.

 * @summary Creates a new membership in a community.
 */
export const createMembership = (
    communityId: string,
    createMembershipBody: CreateMembershipBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MembershipResponse>(
      {url: `/api/v1/communities/${communityId}/memberships`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMembershipBody, signal
    },
      );
    }
  


export const getCreateMembershipMutationOptions = <TError = ErrorType<RestError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMembership>>, TError,{communityId: string;data: CreateMembershipBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMembership>>, TError,{communityId: string;data: CreateMembershipBody}, TContext> => {

const mutationKey = ['createMembership'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMembership>>, {communityId: string;data: CreateMembershipBody}> = (props) => {
          const {communityId,data} = props ?? {};

          return  createMembership(communityId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMembershipMutationResult = NonNullable<Awaited<ReturnType<typeof createMembership>>>
    export type CreateMembershipMutationBody = CreateMembershipBody
    export type CreateMembershipMutationError = ErrorType<RestError>

    /**
 * @summary Creates a new membership in a community.
 */
export const useCreateMembership = <TError = ErrorType<RestError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMembership>>, TError,{communityId: string;data: CreateMembershipBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMembership>>,
        TError,
        {communityId: string;data: CreateMembershipBody},
        TContext
      > => {

      const mutationOptions = getCreateMembershipMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Deletes the membership of the specified user in the community. Requires COMMUNITY_ADMIN or PLATFORM_ADMIN.
 * @summary Removes a user from a community.
 */
export const deleteMembership = (
    communityId: string,
    userId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/communities/${communityId}/memberships/${userId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteMembershipMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMembership>>, TError,{communityId: string;userId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteMembership>>, TError,{communityId: string;userId: string}, TContext> => {

const mutationKey = ['deleteMembership'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMembership>>, {communityId: string;userId: string}> = (props) => {
          const {communityId,userId} = props ?? {};

          return  deleteMembership(communityId,userId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMembershipMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMembership>>>
    
    export type DeleteMembershipMutationError = ErrorType<unknown>

    /**
 * @summary Removes a user from a community.
 */
export const useDeleteMembership = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMembership>>, TError,{communityId: string;userId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMembership>>,
        TError,
        {communityId: string;userId: string},
        TContext
      > => {

      const mutationOptions = getDeleteMembershipMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Changes the role of a user within a community. Requires COMMUNITY_ADMIN or PLATFORM_ADMIN.
 * @summary Updates the role of a membership.
 */
export const updateMembershipRole = (
    communityId: string,
    userId: string,
    updateMembershipRoleBody: UpdateMembershipRoleBody,
 ) => {
      
      
      return customInstance<MembershipResponse>(
      {url: `/api/v1/communities/${communityId}/memberships/${userId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateMembershipRoleBody
    },
      );
    }
  


export const getUpdateMembershipRoleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMembershipRole>>, TError,{communityId: string;userId: string;data: UpdateMembershipRoleBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMembershipRole>>, TError,{communityId: string;userId: string;data: UpdateMembershipRoleBody}, TContext> => {

const mutationKey = ['updateMembershipRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMembershipRole>>, {communityId: string;userId: string;data: UpdateMembershipRoleBody}> = (props) => {
          const {communityId,userId,data} = props ?? {};

          return  updateMembershipRole(communityId,userId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMembershipRoleMutationResult = NonNullable<Awaited<ReturnType<typeof updateMembershipRole>>>
    export type UpdateMembershipRoleMutationBody = UpdateMembershipRoleBody
    export type UpdateMembershipRoleMutationError = ErrorType<unknown>

    /**
 * @summary Updates the role of a membership.
 */
export const useUpdateMembershipRole = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMembershipRole>>, TError,{communityId: string;userId: string;data: UpdateMembershipRoleBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMembershipRole>>,
        TError,
        {communityId: string;userId: string;data: UpdateMembershipRoleBody},
        TContext
      > => {

      const mutationOptions = getUpdateMembershipRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * How much of the member's recorded investment their share of the community's
energy has recovered, and roughly how long the rest would take.

`savedEur` is the estimated value of the self-consumed energy of **all** the
member's supplies in this community, from `startDate` until now, priced per
tariff segment. It prices the **energy term before taxes** only: the power term,
access tolls, charges and electricity tax are all excluded, and VAT is applied
only where the resolved tariff carries a rate. It is computed on each request and
never stored, so it reflects both new consumption and any later correction.
Supplies in the member's other communities are not counted.

`startDate` is the civil date the community first activated a partition
coefficient, and is therefore **community-wide rather than per member**. A
member who joined later has their savings divided by the community's elapsed
days rather than their own, so their apparent daily rate is lower than their
real one and `estimatedRemainingMonths` is correspondingly pessimistic. This is
a known limitation.

Null and zero mean different things throughout. A null `investmentEur` means
none has been recorded, not a contribution of zero; a null `savedEur` means the
community has never shared energy, whereas zero means it has and this member
consumed nothing from it. `estimatedRemainingMonths` is null whenever no rate
can be established, and 0 once the investment is recovered.

`progressRatio` is not capped and exceeds 1 for a member who has recovered more
than they contributed. `tariffSource` is never null and is `ESTIMATE` whenever
any part of the amount came from an estimated tariff, or when no tariff was
consulted at all.

Readable by the member themself and by community admins of this community.
Platform admins are **not** granted access on that basis alone and are answered
404, as is every other caller who may not read it, so the membership's existence
is not disclosed.

 * @summary Retrieves a membership's payback progress.
 */
export const getMembershipPayback = (
    communityId: string,
    userId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MembershipPaybackResponse>(
      {url: `/api/v1/communities/${communityId}/memberships/${userId}/payback`, method: 'GET', signal
    },
      );
    }
  



export const getGetMembershipPaybackQueryKey = (communityId?: string,
    userId?: string,) => {
    return [
    `/api/v1/communities/${communityId}/memberships/${userId}/payback`
    ] as const;
    }

    
export const getGetMembershipPaybackQueryOptions = <TData = Awaited<ReturnType<typeof getMembershipPayback>>, TError = ErrorType<unknown>>(communityId: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembershipPayback>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMembershipPaybackQueryKey(communityId,userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMembershipPayback>>> = ({ signal }) => getMembershipPayback(communityId,userId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(communityId && userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMembershipPayback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMembershipPaybackQueryResult = NonNullable<Awaited<ReturnType<typeof getMembershipPayback>>>
export type GetMembershipPaybackQueryError = ErrorType<unknown>


export function useGetMembershipPayback<TData = Awaited<ReturnType<typeof getMembershipPayback>>, TError = ErrorType<unknown>>(
 communityId: string,
    userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembershipPayback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMembershipPayback>>,
          TError,
          Awaited<ReturnType<typeof getMembershipPayback>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMembershipPayback<TData = Awaited<ReturnType<typeof getMembershipPayback>>, TError = ErrorType<unknown>>(
 communityId: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembershipPayback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMembershipPayback>>,
          TError,
          Awaited<ReturnType<typeof getMembershipPayback>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMembershipPayback<TData = Awaited<ReturnType<typeof getMembershipPayback>>, TError = ErrorType<unknown>>(
 communityId: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembershipPayback>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves a membership's payback progress.
 */

export function useGetMembershipPayback<TData = Awaited<ReturnType<typeof getMembershipPayback>>, TError = ErrorType<unknown>>(
 communityId: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembershipPayback>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMembershipPaybackQueryOptions(communityId,userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Aggregates the consumption data stored for **every** supply the member owns in
this community into energy totals and two ratios, on a 0-1 scale. Supplies in the
member's other communities are not counted.

- `selfSufficiencyRatio`: self-consumed energy divided by total consumed energy.
- `selfConsumptionRatio`: self-consumed energy divided by the assigned energy.

Every supply is computed over the same period, exactly as the per-supply
energy-metrics endpoint computes it, and the results are added up: the energy
totals are summed across supplies and each ratio is derived **once** from those
sums, never by averaging the per-supply ratios. A ratio whose summed denominator
is zero is returned as `null`, never as `0`.

**Period:**
The period is resolved in exactly one of three ways, and the resolved bounds are
always reported in `period`, also when the caller supplied them.

- `startDate` and `endDate`: an explicit period, with the same semantics as the
  per-supply endpoint. They must be supplied together, and a `startDate` after
  the `endDate` is a bad request. **Both bounds are inclusive**: a single
  calendar day runs from `00:00` to `23:00` of that day.
- `period=LATEST_PUBLISHED_MONTH`: the most recent complete calendar month, in
  the community's time zone, in which any of the member's supplies has stored
  assigned production (self-consumed or surplus energy). The distributor
  publishes a month's assigned production only some days after it ends, so this
  is not necessarily the previous month: an unpublished previous month is
  skipped and the search continues backwards through the 24 complete months
  before the current one. The current month is never a candidate. The period
  runs from `00:00` of the first day to `23:00` of the last day. Combining it
  with `startDate` or `endDate` is a bad request.
- Neither: from the earliest to the latest record stored for any of the member's
  supplies.

When no period can be resolved -- no assigned production in the search window, no
stored record at all, or no supplies to search -- the response is still
successful, with null period bounds, zero totals and null ratios.

**Coverage:**
`coverage.hoursWithData` counts the hourly records found across every supply.
`coverage.expectedHours` is the number of hours the period spans **times the
number of supplies of the membership**, so a single supply without any record
lowers coverage even when every other supply is complete. `supplyCount` and
`suppliesWithData` tell one silent supply apart from gaps spread across all of
them. Hours without a record are left out of the sums; they are never counted as
zero.

**Savings:**
`savings.amountEur` is an **estimate** of what the self-consumed energy of all
the member's supplies was worth, pricing the **energy term before taxes** only,
exactly as the per-supply endpoint does, and summed before being rounded.
It is `null` only when no period could be resolved; whenever a period exists it
is a figure, `0.00` when nothing was priced. An explicit period always resolves,
so it never yields `null`. `savings.tariffSource` is `ESTIMATE` when any part of
any supply was priced with the estimate, and `savings.estimatedPrice` then carries
the estimated price; it is `null` when every supply was priced with its contracted
tariff, and when nothing was priced with the estimate.

Readable by the member themself and by community admins of this community.
Platform admins are **not** granted access on that basis alone and are answered
404, as is every other caller who may not read it, so the membership's existence
is not disclosed. A membership without supplies is answered successfully, not
with 404.

 * @summary Retrieves the energy metrics of every supply of a membership, added up.
 */
export const getMembershipEnergyMetrics = (
    communityId: string,
    userId: string,
    params?: GetMembershipEnergyMetricsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<MembershipEnergyMetricsResponse>(
      {url: `/api/v1/communities/${communityId}/memberships/${userId}/energy-metrics`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetMembershipEnergyMetricsQueryKey = (communityId?: string,
    userId?: string,
    params?: GetMembershipEnergyMetricsParams,) => {
    return [
    `/api/v1/communities/${communityId}/memberships/${userId}/energy-metrics`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetMembershipEnergyMetricsQueryOptions = <TData = Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError = ErrorType<unknown>>(communityId: string,
    userId: string,
    params?: GetMembershipEnergyMetricsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMembershipEnergyMetricsQueryKey(communityId,userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMembershipEnergyMetrics>>> = ({ signal }) => getMembershipEnergyMetrics(communityId,userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(communityId && userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMembershipEnergyMetricsQueryResult = NonNullable<Awaited<ReturnType<typeof getMembershipEnergyMetrics>>>
export type GetMembershipEnergyMetricsQueryError = ErrorType<unknown>


export function useGetMembershipEnergyMetrics<TData = Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError = ErrorType<unknown>>(
 communityId: string,
    userId: string,
    params: undefined |  GetMembershipEnergyMetricsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMembershipEnergyMetrics>>,
          TError,
          Awaited<ReturnType<typeof getMembershipEnergyMetrics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMembershipEnergyMetrics<TData = Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError = ErrorType<unknown>>(
 communityId: string,
    userId: string,
    params?: GetMembershipEnergyMetricsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMembershipEnergyMetrics>>,
          TError,
          Awaited<ReturnType<typeof getMembershipEnergyMetrics>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMembershipEnergyMetrics<TData = Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError = ErrorType<unknown>>(
 communityId: string,
    userId: string,
    params?: GetMembershipEnergyMetricsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieves the energy metrics of every supply of a membership, added up.
 */

export function useGetMembershipEnergyMetrics<TData = Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError = ErrorType<unknown>>(
 communityId: string,
    userId: string,
    params?: GetMembershipEnergyMetricsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMembershipEnergyMetrics>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMembershipEnergyMetricsQueryOptions(communityId,userId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




