/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  CommunityResponse
} from '.././models';


export const getGetCommunityByIdResponseMock = (overrideResponse: Partial< CommunityResponse > = {}): CommunityResponse => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), code: faker.string.alpha({length: {min: 10, max: 20}}), legalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), enabled: faker.datatype.boolean(), adminNames: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), memberCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), supplyPointCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), ...overrideResponse})

export const getUpdateCommunityResponseMock = (overrideResponse: Partial< CommunityResponse > = {}): CommunityResponse => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), code: faker.string.alpha({length: {min: 10, max: 20}}), legalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), enabled: faker.datatype.boolean(), adminNames: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), memberCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), supplyPointCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), ...overrideResponse})

export const getGetAllCommunitiesResponseMock = (): CommunityResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), code: faker.string.alpha({length: {min: 10, max: 20}}), legalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), enabled: faker.datatype.boolean(), adminNames: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), memberCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), supplyPointCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined})})))

export const getCreateCommunityResponseMock = (overrideResponse: Partial< CommunityResponse > = {}): CommunityResponse => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), code: faker.string.alpha({length: {min: 10, max: 20}}), legalId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), address: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), enabled: faker.datatype.boolean(), adminNames: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), memberCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), supplyPointCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), ...overrideResponse})


export const getGetCommunityByIdMockHandler = (overrideResponse?: CommunityResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CommunityResponse> | CommunityResponse)) => {
  return http.get('*/api/v1/communities/:communityId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCommunityByIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getUpdateCommunityMockHandler = (overrideResponse?: CommunityResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CommunityResponse> | CommunityResponse)) => {
  return http.put('*/api/v1/communities/:communityId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateCommunityResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetAllCommunitiesMockHandler = (overrideResponse?: CommunityResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CommunityResponse[]> | CommunityResponse[])) => {
  return http.get('*/api/v1/communities', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAllCommunitiesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCreateCommunityMockHandler = (overrideResponse?: CommunityResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CommunityResponse> | CommunityResponse)) => {
  return http.post('*/api/v1/communities', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateCommunityResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getEnableCommunityMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void)) => {
  return http.post('*/api/v1/communities/:communityId/enable', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getDisableCommunityMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void)) => {
  return http.post('*/api/v1/communities/:communityId/disable', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}
export const getCommunitiesMock = () => [
  getGetCommunityByIdMockHandler(),
  getUpdateCommunityMockHandler(),
  getGetAllCommunitiesMockHandler(),
  getCreateCommunityMockHandler(),
  getEnableCommunityMockHandler(),
  getDisableCommunityMockHandler()
]
