services:
  conluzweb:
    # Uncomment this and comment the build block if you want to build the last image pushed to GitHub Container Registry
    # image: ghcr.io/lucoenergia/conluz-web:latest
    container_name: conluzweb
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped
    environment:
      - CONLUZ_API_URL=http://localhost:8443
