services:
  conluzweb:
    image: conluzweb
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3001:80" 
    restart: unless-stopped
    environment:
      - CONLUZ_API_URL=http://localhost:8443
