// Entry for the claude.ai/design sync: the presentational components of
// conluz-web that render with only the theme and a router. Components that
// fetch, mutate, or read auth/community context are left out on purpose.
export { ConluzProvider } from "./ConluzProvider";
export { Mui, Icons } from "./primitives";
export { theme } from "../../src/theme";
export { colors, alphas, shadows, radii, fontSizes, motion, interactiveTransition } from "../../src/theme/tokens";
export { sxStyles } from "../../src/theme/sx";
// Pure selectors that turn an agreement + its coefficients into the state the
// lifecycle banner and spine render, so designs derive it the way the app does.
export { selectSharingAgreementNextStep } from "../../src/pages/production/selectSharingAgreementNextStep";
export { selectSharingAgreementLifecycleView } from "../../src/pages/production/sharingAgreementLifecycle";

export { ActionStatus } from "../../src/components/ActionStatus/ActionStatus";
export { AppAccordion } from "../../src/components/AppAccordion/AppAccordion";
export { LoadingAppAccordion } from "../../src/components/AppAccordion/LoadingAppAccordion";
export { AppCard } from "../../src/components/AppCard/AppCard";
export { AttentionPanel } from "../../src/components/AttentionPanel/AttentionPanel";
export { BreadCrumb } from "../../src/components/Breadcrumb/BreadCrumb";
export { CapabilityLoadError } from "../../src/components/Auth/CapabilityLoadError";
export { CardGrid } from "../../src/components/CardGrid/CardGrid";
export { LoadingCardGrid } from "../../src/components/CardGrid/LoadingCardGrid";
export { CoefficientActionsMenuItems } from "../../src/components/CoefficientActionsMenu/CoefficientActionsMenu";
export { CoefficientHistory } from "../../src/components/CoefficientHistory/CoefficientHistory";
export { CommunityScopeHeader } from "../../src/components/CommunityScopeHeader/CommunityScopeHeader";
export { CommunityStatusChip } from "../../src/components/CommunityStatusChip/CommunityStatusChip";
export { DetailHeader } from "../../src/components/DetailHeader/DetailHeader";
export { EmptyState } from "../../src/components/EmptyState/EmptyState";
export { FilterChipsBar } from "../../src/components/FilterChips/FilterChipsBar";
export { DropdownSelector } from "../../src/components/Forms/DropdownSelector";
export { PasswordInput } from "../../src/components/Forms/PasswordInput";
export { PasswordPolicyHint } from "../../src/components/Forms/PasswordPolicyHint";
export { Graph } from "../../src/components/Graph/Graph";
export { GraphBar } from "../../src/components/Graph/GraphBar";
export { GraphCard } from "../../src/components/Graph/GraphCard";
export { GraphFilter } from "../../src/components/Graph/GraphFilter";
export { LoadingGraphCard } from "../../src/components/Graph/LoadingGraphCard";
export { MultiSeriesBar } from "../../src/components/Graph/MultiSeriesBar";
export { Logo } from "../../src/components/Header/Logo";
export { LabeledIcon } from "../../src/components/LabeledIcon/LabeledIcon";
export { ListTable, ListTableHeaderText } from "../../src/components/ListTable/ListTable";
export { RowActionsMenu } from "../../src/components/ListTable/RowActionsMenu";
export { LoadErrorAlert } from "../../src/components/LoadErrorAlert/LoadErrorAlert";
export { DisplayMenu } from "../../src/components/Menu/DisplayMenu";
export { MenuLinkItem } from "../../src/components/Menu/MenuLinkItem";
export { MenuTemplate } from "../../src/components/Menu/MenuTemplate";
export { SideMenu } from "../../src/components/Menu/SideMenu";
export { AlertModal } from "../../src/components/Modals/AlertModal";
export { AppModal } from "../../src/components/Modals/AppModal";
export { BasicModal } from "../../src/components/Modals/BasicModal";
export { ConfirmationModal } from "../../src/components/Modals/ConfirmationModal";
export { CoefficientDialogErrorPanel, CoefficientTargetSummary } from "../../src/components/Modals/coefficientLifecycleDialogHelpers";
export { DeleteSuccessModal } from "../../src/components/Modals/DeleteSuccessModal";
export { DisablePartnerConfirmationModal } from "../../src/components/Modals/DisablePartnerConfirmationModal";
export { DisablePartnerSuccessModal } from "../../src/components/Modals/DisablePartnerSuccessModal";
export { DisableSuccessModal } from "../../src/components/Modals/DisableSuccessModal";
export { EnablePartnerConfirmationModal } from "../../src/components/Modals/EnablePartnerConfirmationModal";
export { EnableSuccessModal } from "../../src/components/Modals/EnableSuccesModal";
export { GrantPlatformAdminConfirmationModal } from "../../src/components/Modals/GrantPlatformAdminConfirmationModal";
export { PlatformAdminSuccessModal } from "../../src/components/Modals/PlatformAdminSuccessModal";
export { RevokePlatformAdminConfirmationModal } from "../../src/components/Modals/RevokePlatformAdminConfirmationModal";
export { ApplyCoefficientDateConfirmationModal } from "../../src/components/Modals/ApplyCoefficientDateConfirmationModal";
export { CloseCoefficientConfirmationModal } from "../../src/components/Modals/CloseCoefficientConfirmationModal";
export { CorrectCoefficientDateConfirmationModal } from "../../src/components/Modals/CorrectCoefficientDateConfirmationModal";
export { DeactivateOrReopenCoefficientConfirmationModal } from "../../src/components/Modals/DeactivateOrReopenCoefficientConfirmationModal";
export { DeleteConfirmationModal } from "../../src/components/Modals/DeleteConfirmationModal";
export { DeleteSharingAgreementConfirmationModal } from "../../src/components/Modals/DeleteSharingAgreementConfirmationModal";
export { DisableConfirmationModal } from "../../src/components/Modals/DisableConfirmationModal";
export { EnableConfirmationModal } from "../../src/components/Modals/EnableConfirmationModal";
export { PublishSharingAgreementConfirmationModal } from "../../src/components/Modals/PublishSharingAgreementConfirmationModal";
export { RevertSharingAgreementToDraftConfirmationModal } from "../../src/components/Modals/RevertSharingAgreementToDraftConfirmationModal";
export { PaginatedList } from "../../src/components/PaginatedList/PaginatedList";
export { PaginationOutlined } from "../../src/components/Pagination/Pagination";
export { PlantCard } from "../../src/components/PlantCard/PlantCard";
export { PlantDetailHeader } from "../../src/components/PlantDetailHeader/PlantDetailHeader";
export { PlatformKpiCard } from "../../src/components/PlatformKpiCard/PlatformKpiCard";
export { RecordList } from "../../src/components/RecordList/RecordList";
export { ResultStatus } from "../../src/components/ResultStatus/ResultStatus";
export { RouteFallback } from "../../src/components/RouteFallback/RouteFallback";
export { SearchBar } from "../../src/components/SearchBar/SearchBar";
export { SectionHeading } from "../../src/components/SectionHeading/SectionHeading";
export { SharingAgreementActionButton } from "../../src/components/SharingAgreementActionButton/SharingAgreementActionButton";
export { SharingAgreementApplicationPanel } from "../../src/components/SharingAgreementApplicationPanel/SharingAgreementApplicationPanel";
export { SharingAgreementCard } from "../../src/components/SharingAgreementCard/SharingAgreementCard";
export { SharingAgreementCoefficientCard, SharingAgreementCoefficientTableRow } from "../../src/components/SharingAgreementCoefficientRow/SharingAgreementCoefficientRow";
export { SharingAgreementCoefficientSumGauges } from "../../src/components/SharingAgreementCoefficientSumGauges/SharingAgreementCoefficientSumGauges";
export { SharingAgreementLifecycleSpine } from "../../src/components/SharingAgreementLifecycleSpine/SharingAgreementLifecycleSpine";
export { SharingAgreementNextStepBanner } from "../../src/components/SharingAgreementNextStepBanner/SharingAgreementNextStepBanner";
export { SharingAgreementOutgoingSupplies } from "../../src/components/SharingAgreementOutgoingSupplies/SharingAgreementOutgoingSupplies";
export { SharingAgreementStatusChip } from "../../src/components/SharingAgreementStatusChip/SharingAgreementStatusChip";
export { SharingAgreementTimeline } from "../../src/components/SharingAgreementTimeline/SharingAgreementTimeline";
export { Stat } from "../../src/components/Stat/Stat";
export { LoadingStat } from "../../src/components/Stat/LoadingStat";
export { StatsCard } from "../../src/components/StatsCard/StatsCard";
export { SupplyCard } from "../../src/components/SupplyCard/SupplyCard";
export { SupplyDetailCard } from "../../src/components/SupplyDetailCard/SupplyDetailCard";
export { LoadingSupplyDetailCard } from "../../src/components/SupplyDetailCard/loadingSupplyDetailCard";
export { SupplyDetailHeader } from "../../src/components/SupplyDetailHeader/SupplyDetailHeader";
export { SupplyStatsCard } from "../../src/components/SupplyStatsCard/SupplyStatsCard";
export { LoadingSupplyStatsCard } from "../../src/components/SupplyStatsCard/LoadingSupplyStatsCard";
export { SupportCard } from "../../src/components/SupportCard/SupportCard";
export { TagComponent } from "../../src/components/Tag/Tag";
export { UserForm } from "../../src/components/UserForm/UserForm";
