/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export interface ActivateCoefficientsBody {
  /** The date the distributor applied these coefficients (or the corrected date, if any of them are already active). Backdating is allowed; future dates are rejected. */
  appliedOn: string;
  /**
   * The coefficients to activate or correct, all belonging to this agreement.
   * @minItems 1
   */
  coefficientIds: string[];
}
