/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export interface CloseCoefficientsBody {
  /** The date this coefficient's coverage ends (the exit case: the supply left the distribution), or the corrected date if it was already closed by an earlier call. */
  closedOn: string;
  /**
   * The coefficients to close or correct, all belonging to this agreement.
   * @minItems 1
   */
  coefficientIds: string[];
}
