/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export interface CommunityResponse {
  id?: string;
  name?: string;
  code?: string;
  legalId?: string;
  address?: string;
  enabled?: boolean;
  /** Display names of community administrators */
  adminNames?: string[];
  /** Total number of members in the community */
  memberCount?: number;
  /** Total number of supply points in the community */
  supplyPointCount?: number;
}
