/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateSupplyBody {
  /** @minLength 1 */
  code: string;
  /**
   * The DNI/NIE/NIF of the existing user who owns the supply. It is normalised before the owner is looked up: whitespace (including the no-break space), dots and hyphens are removed and letters are upper-cased, so 12.345.678-a and 12345678A are the same identifier.
   * @minLength 1
   */
  personalId: string;
  /** @minLength 1 */
  address: string;
  addressRef?: string;
  name?: string;
  communityId: string;
}
