/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUserBodyRole } from './createUserBodyRole';

export interface CreateUserBody {
  /** @minLength 1 */
  personalId: string;
  /** @minimum 0 */
  number: number;
  /** @minLength 1 */
  fullName: string;
  address?: string;
  /** @minLength 1 */
  email: string;
  phoneNumber?: string;
  /** @minLength 1 */
  password: string;
  role: CreateUserBodyRole;
}
