/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export type CreateUserBodyRole = typeof CreateUserBodyRole[keyof typeof CreateUserBodyRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserBodyRole = {
  PARTNER: 'PARTNER',
  ADMIN: 'ADMIN',
  OBSERVER: 'OBSERVER',
} as const;
