/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import type { CreatePlantBodyInverterProvider } from './createPlantBodyInverterProvider';

export interface CreatePlantBody {
  /**
   * The plant identifier assigned by the inverter provider (currently Huawei). Used verbatim as the station_code tag in InfluxDB: this is the join key between the PostgreSQL plant row and its time series. It is not a CUPS and not a CAU -- the regulator's code is regulatory_code.
   * @minLength 1
   */
  providerCode: string;
  /** The identifier assigned by the regulator. In Spain this is the CAU (Codigo de Autoconsumo). It is not the provider's station code (provider_code) and not a CUPS. */
  regulatoryCode?: string;
  /** @minLength 1 */
  name: string;
  description?: string;
  /** @minLength 1 */
  supplyCode: string;
  inverterProvider: CreatePlantBodyInverterProvider;
  connectionDate?: string;
  /** @minLength 1 */
  address: string;
  totalPower: number;
}
