/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import type { CurrentUserResponseAddress } from './currentUserResponseAddress';
import type { CurrentUserResponsePhoneNumber } from './currentUserResponsePhoneNumber';
import type { CurrentUserResponseMemberships } from './currentUserResponseMemberships';
import type { UserCapabilitiesResponse } from './userCapabilitiesResponse';
import type { PlatformCapabilitiesResponse } from './platformCapabilitiesResponse';

/**
 * The authenticated caller's own user, with what they may do.
 */
export interface CurrentUserResponse {
  id: string;
  personalId: string;
  number: number;
  fullName: string;
  address: CurrentUserResponseAddress;
  email: string;
  phoneNumber: CurrentUserResponsePhoneNumber;
  enabled: boolean;
  memberships: CurrentUserResponseMemberships;
  /** What the caller may do with their own user record. */
  capabilities: UserCapabilitiesResponse;
  /** What the caller may do on the platform as a whole, independently of any one resource. */
  platformCapabilities: PlatformCapabilitiesResponse;
  isPlatformAdmin: boolean;
}
