/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export type GetPartitionCoefficientAtTimestampParams = {
/**
 * ISO-8601 timestamp
 */
timestamp: string;
/**
 * Optional plant filter. When omitted, every plant the supply participates in is included.
 */
plantId?: string;
};
