/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Savings divided by investment. Not capped: a member who has recovered more than they contributed reports a value above 1. Null when either amount is null.
 */
export type MembershipPaybackResponseProgressRatio = number | null;
