/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

/**
 * What the caller may do with this membership.
 */
export interface MembershipCapabilitiesResponse {
  /** Whether the caller may change this membership's role. */
  canUpdateRole: boolean;
  /** Whether the caller may remove this membership from the community. */
  canDelete: boolean;
  /** Whether the caller may set or clear the investment recorded on this membership. */
  canManageInvestment: boolean;
  /** Whether the caller may read this membership's payback progress. Either an admin of the community, or the member themselves. */
  canReadPayback: boolean;
}
