/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import type { MembershipMonthlyConsumptionBucketResponseSavingsEur } from './membershipMonthlyConsumptionBucketResponseSavingsEur';
import type { MembershipMonthlyConsumptionBucketResponseTariffSource } from './membershipMonthlyConsumptionBucketResponseTariffSource';

export interface MembershipMonthlyConsumptionBucketResponse {
  /** First day of the month, a local calendar date in the community's time zone. */
  date: string;
  /** Local time the month starts at in the community's time zone: always midnight. */
  time: string;
  /** Energy consumed from the grid over the month by every supply of the membership, in kWh. 0 when no supply stored a record. */
  consumptionKWh: number;
  /** Energy exported to the grid over the month by every supply of the membership, in kWh. */
  surplusEnergyKWh: number;
  /** Energy generated and assigned to every supply of the membership over the month, in kWh. */
  generationEnergyKWh: number;
  /** Energy generated and consumed on site over the month by every supply of the membership, in kWh. */
  selfConsumptionEnergyKWh: number;
  /** Estimated amount the month's self-consumed energy saved across every supply that stored a record, in euros, rounded to cents. Null when no supply stored a record that month: a month with nothing stored is not a month that saved nothing. Unlike the per-supply series, which never reports null here. A supply that did store a record with no self-consumption is a measured zero and makes the amount 0.00, not null. Null exactly when tariffSource is null. */
  savingsEur: MembershipMonthlyConsumptionBucketResponseSavingsEur;
  /** Whether the prices behind savingsEur are the supplies' contracted tariffs or an estimate. A single estimated stretch of any supply makes the whole amount an estimate. Null exactly when savingsEur is null: with no amount there is nothing whose prices to describe. */
  tariffSource: MembershipMonthlyConsumptionBucketResponseTariffSource;
  /** Number of supplies the member currently owns in the community. The model records no date a supply joined, so the same count applies to every month, including months before a supply started reporting. */
  supplyCount: number;
  /** Number of those supplies that stored a monthly record for this month. Measured from stored monthly records, month by month, whereas the aggregated energy metrics measure their suppliesWithData from hourly records over the whole period: same name and intent, different unit, so the two figures are not comparable across endpoints. Below supplyCount, the month is incomplete. */
  suppliesWithData: number;
}
