/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Estimated amount saved over the period by every supply of the membership, in euros, rounded to cents. Null only when no period could be resolved; whenever a period exists it is a figure, 0.00 when nothing was priced.
 */
export type MembershipEnergyMetricsSavingsResponseAmountEur = number | null;
