/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import type { EstimatedPriceResponse } from './estimatedPriceResponse';

/**
 * The estimated energy-term price, before taxes, the amount was priced with. Present only when the estimated price was used to price at least part of the period for at least one supply; null when every supply was priced with its contracted tariff, and when nothing was priced with the estimate at all.
 */
export type MembershipEnergyMetricsSavingsResponseEstimatedPrice = EstimatedPriceResponse | null;
