/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Where the prices behind savedEur came from. ESTIMATE when any part of the figure was priced from an estimated tariff rather than a contracted one, and also when no tariff was consulted at all. Never null: an amount derived from an estimate is not interchangeable with one derived from a real tariff.
 */
export type MembershipPaybackResponseTariffSource = typeof MembershipPaybackResponseTariffSource[keyof typeof MembershipPaybackResponseTariffSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MembershipPaybackResponseTariffSource = {
  REAL_TARIFF: 'REAL_TARIFF',
  ESTIMATE: 'ESTIMATE',
} as const;
