/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export interface MembershipEnergyMetricsCoverageResponse {
  /** Number of hourly consumption records found in the period, summed across every supply of the membership */
  hoursWithData: number;
  /** Number of hours the period spans, times the number of supplies of the membership. A supply without any record therefore lowers coverage even when the rest are complete. Accounts for daylight saving transitions. */
  expectedHours: number;
  /** Number of supplies of the membership in this community */
  supplyCount: number;
  /** Number of those supplies with at least one hourly record in the period */
  suppliesWithData: number;
}
