/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export interface PartitionCoefficientResponse {
  /** Internal unique identifier */
  id?: string;
  /** Supply this coefficient belongs to */
  supplyId?: string;
  /** Partition coefficient value */
  coefficient?: number;
  /** Start of the period during which this coefficient is active (inclusive) */
  validFrom?: string;
  /** End of the period (exclusive). Null means this is the currently active coefficient. */
  validTo?: string;
  /** Timestamp when this record was created */
  createdAt?: string;
}
