/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

/**
 * What the caller may do from this partition coefficient period.
 */
export interface PartitionCoefficientCapabilitiesResponse {
  /** Whether the caller may open the sharing agreement referenced by this period (GET /api/v1/plants/{plantId}/sharing-agreements/{sharingAgreementId}). The reference carries no capabilities of its own, so the period says whether following it would succeed. */
  canReadSharingAgreement: boolean;
}
