/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export interface PasswordResetBody {
  /** The token from the password reset link: everything after the `#` of `<web client>/reset-password#<token>`, exactly as it appears there. */
  token: string;
  /**
   * The new password. Between 15 and 64 characters, counting each Unicode code point as one, and no more than 72 bytes once UTF-8 encoded. Any character is accepted, including spaces and non-ASCII letters; there are no composition rules, and the value is never trimmed or transformed. It must differ from the current password.
   * @minLength 15
   */
  newPassword: string;
}
