/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import type { PartitionCoefficientResponse } from './partitionCoefficientResponse';
import type { BulkErrorString } from './bulkErrorString';

export interface RegisterPartitionCoefficientsWithFileResponse {
  created?: PartitionCoefficientResponse[];
  errors?: BulkErrorString[];
  /** Warning message when the sum of all active coefficients in the community deviates from 100 by more than 0.0001 at the effectiveAt instant. Null when the sum is correct. */
  communityCoefficientSumWarning?: string;
}
