/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export interface ReopenCoefficientsBody {
  /**
   * The coefficients to reopen (retract an authored close), all belonging to this agreement. Rejected when the close was written by the activation cascade rather than authored.
   * @minItems 1
   */
  coefficientIds: string[];
}
