/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Identifier of the user who last edited the agreement. Null means it has never been edited since creation
 */
export type SharingAgreementResponseUpdatedBy = string | null;
