/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export interface SharingAgreementFileResponse {
  /** Internal unique identifier of the stored file */
  id: string;
  /** Original filename as uploaded */
  filename: string;
  /** Date and time the file was uploaded */
  uploadedAt: string;
}
