/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Share of the energy consumed that came from the community rather than from the grid, on a 0-1 scale. Null when nothing was consumed in the period.
 */
export type SupplyEnergyMetricsResponseSelfSufficiencyRatio = number | null;
