/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from './userResponse';

export interface SupplyResponse {
  /** Internal unique identifier of the supply */
  id?: string;
  /** Code that identifies the supply */
  code?: string;
  /** Owner of the supply */
  user?: UserResponse;
  /** Name of the supply */
  name?: string;
  /** Address of the supply */
  address?: string;
  /** Address of the supply */
  partitionCoefficient?: number;
  /** Whether the supply is enabled or disabled */
  enabled?: boolean;
  /** Date on which the supply point was registered as valid */
  datadisValidDateFrom?: string;
  /** Name of the distribution company */
  datadisDistributor?: string;
  /** Code of the distribution company */
  datadisDistributorCode?: string;
  /** Type of measurement point */
  datadisPointType?: number;
  /** Whether is an authorized third parth supply or not */
  datadisIsThirdParty?: boolean;
  /** MAC address of the Shelly */
  shellyMac?: string;
  /** Unique identifier of the Shelly */
  shellyId?: string;
  /** MQTT prefix for the Shelly */
  shellyMqttPrefix?: string;
}
