/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import type { SupplyEnergyMetricsSupplyResponseName } from './supplyEnergyMetricsSupplyResponseName';

export interface SupplyEnergyMetricsSupplyResponse {
  /** Internal unique identifier of the supply */
  id: string;
  /** Code that identifies the supply */
  code: string;
  /** Name of the supply */
  name: SupplyEnergyMetricsSupplyResponseName;
}
