/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */
import type { SupplyEnergyMetricsSavingsResponseAmountEur } from './supplyEnergyMetricsSavingsResponseAmountEur';
import type { SupplyEnergyMetricsSavingsResponseTariffSource } from './supplyEnergyMetricsSavingsResponseTariffSource';

export interface SupplyEnergyMetricsSavingsResponse {
  /** Estimated amount saved over the period, in euros, rounded to cents. Null when no period could be resolved, which is not the same as a saving of zero. */
  amountEur: SupplyEnergyMetricsSavingsResponseAmountEur;
  /** Whether the prices behind the amount are the supply's contracted tariff or an estimate. A single estimated stretch of the period makes the whole amount an estimate. */
  tariffSource: SupplyEnergyMetricsSavingsResponseTariffSource;
}
