/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUserBody {
  /** @minimum 0 */
  number: number;
  /**
   * The user's DNI/NIE/NIF, unique among users. It is normalised before it is stored or compared: whitespace (including the no-break space), dots and hyphens are removed and letters are upper-cased, so 12.345.678-a and 12345678A are the same identifier.
   * @minLength 1
   */
  personalId: string;
  /** @minLength 1 */
  fullName: string;
  address?: string;
  /** @minLength 1 */
  email: string;
  phoneNumber?: string;
}
