/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Conluz API
 * Conluz is an API-driven application designed for the efficient management of an energy community,enabling the administration of community members and their corresponding supply points and the retrieval of consumption, production data.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Map of communityId (UUID string) to the user's role in that community
 */
export type UserResponseMemberships = {[key: string]: 'COMMUNITY_MEMBER' | 'COMMUNITY_ADMIN'};
